# Generated by Django 3.1 on 2020-12-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAlly',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('avatar_type', models.IntegerField(null=True)),
                ('last_shard_transfer', models.IntegerField(null=True)),
                ('home_world_id', models.IntegerField(null=True)),
                ('group_tag', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('troop_kills', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('previous_cost', models.IntegerField(null=True)),
                ('biome1_attack_multiplier', models.IntegerField(null=True)),
                ('biome2_attack_multiplier', models.IntegerField(null=True)),
                ('biome3_attack_multiplier', models.IntegerField(null=True)),
                ('biome4_attack_multiplier', models.IntegerField(null=True)),
                ('biome5_attack_multiplier', models.IntegerField(null=True)),
                ('biome6_attack_multiplier', models.IntegerField(null=True)),
                ('biome7_attack_multiplier', models.IntegerField(null=True)),
                ('biome8_attack_multiplier', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_owner', to='allies.currentally')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAlly',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('avatar_type', models.IntegerField(null=True)),
                ('last_shard_transfer', models.IntegerField(null=True)),
                ('home_world_id', models.IntegerField(null=True)),
                ('group_tag', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('troop_kills', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('previous_cost', models.IntegerField(null=True)),
                ('biome1_attack_multiplier', models.IntegerField(null=True)),
                ('biome2_attack_multiplier', models.IntegerField(null=True)),
                ('biome3_attack_multiplier', models.IntegerField(null=True)),
                ('biome4_attack_multiplier', models.IntegerField(null=True)),
                ('biome5_attack_multiplier', models.IntegerField(null=True)),
                ('biome6_attack_multiplier', models.IntegerField(null=True)),
                ('biome7_attack_multiplier', models.IntegerField(null=True)),
                ('biome8_attack_multiplier', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historical_owner', to='allies.currentally')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
