# Generated by Django 3.1 on 2020-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentally',
            name='avatar_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalally',
            name='avatar_id',
            field=models.IntegerField(null=True),
        ),
    ]
