# Generated by Django 3.1 on 2020-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0002_auto_20201215_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentally',
            name='group_tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalally',
            name='group_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
