# Generated by Django 3.1 on 2020-12-15 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0003_auto_20201215_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalally',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
