# Generated by Django 3.1 on 2020-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0005_auto_20201215_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentAlly',
            new_name='Ally',
        ),
        migrations.AlterField(
            model_name='historicalally',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
