# Generated by Django 3.1 on 2020-12-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0007_auto_20201217_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentAlly',
            new_name='Ally',
        ),
    ]
