# Generated by Django 3.2.5 on 2021-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allies', '0010_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
